"""Add tg user table

Revision ID: 3df86d2d33f3
Revises:
Create Date: 2022-04-24 16:49:41.702368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3df86d2d33f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tg_user',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('is_bot', sa.Boolean(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('language_code', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('pk'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_user')
    # ### end Alembic commands ###
