version: "3.5"


services:
  #================================
  #    POSTGRESQL DATABASE GUI
  #================================
  crypto-alarm-postgresql-gui:
    container_name: crypto-alarm-postgresql-gui
    image: dpage/pgadmin4
    hostname: crypto-alarm-postgresql-gui
    ports:
      - 5050:80
    volumes:
       - ../.data/pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - crypto-alarm-postgresql
    networks:
      - crypto-alarm-network
    restart: always


#================================
#         NETWORK
#================================
networks:
  crypto-alarm-network:
    external:
      name: crypto-alarm-network